### PR TITLE
Reddit

### PR DESCRIPTION
**Pull request by prolajumokeoni**
### Active records

- Created a similar clone of the micro-reddit application 
- Users can create a post, edit and delete post
- User also need to signup before they can login 
- User can add comments
#### Implemented changes requested from previous review

### CODE REVIEW

**Review by mke2111 — CHANGES_REQUESTED** [review]
# STATUS: CHANGES REQUIRED 🔴 ♻️ 

## Hey Happy Coders, 👋🏽 
**This is a great project you have going on, well-done lads**. 

### Well-done 💯 
    1. Users and links can be created successfully.

**However, there are a few sections to improve before your project is approved.** 🔴 
<hr>

### REQUIRED

- [ ] Add instructions on how to set up the project locally within the readme file. Make the instructions very clear.

- [ ] You are lacking a comments table in your schema.
- A comment can be created including a body field. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/building_with_active_record/creatingComment.png) from Odin Project)
- validations are present for the body ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/building_with_active_record/commentValidation.png) from Odin Project)
- A comment belongs to both the user and the link.

- [ ] The users' table needs a username column. This should be validated.

- [ ] A user has many links and comments
- [ ] A link has many comments and belongs to a user.
- [ ] Add validations for the user and the link.

#

### Kindly make all the requested changes and submit another CRR. 💯 

**Cheers 🍹 and Happy coding 💻** 

<hr>

Mention @mke2111 in this thread and I'll be glad to help. 😄 
### Best regards
Slack 🆘  Roy Mukuye
Twitter 🐦  [Roy Mukuye](https://twitter.com/Roymkenya)
LinkedIn 🔗  [Roy Mukuye](https://www.linkedin.com/in/roy-mukuye/)

**Review by george-shammar — CHANGES_REQUESTED** [review]
### **STATUS: CHANGES REQUIRED** :recycle: :recycle: :construction: 

Good job, team and thanks for implementing some of the required changes.
**Highlights**
- You now have a comments table and comments can now be created as well. :+1: :clap: 

Please see below the required changes:

- [ ] Please add validations to your comments body.
- [ ] The users' table needs a username column. This should be validated.
- [ ] A user should have many links and comments. You have not added associations between user and comment in the user's model.
- [ ]  Add validations for the user and the link.

Please make the required changes and submit another CRR when you're ready.

Cheers and happy coding. :smile:

**Review by mke2111 — CHANGES_REQUESTED** [review]
# STATUS: CHANGES REQUIRED 🔴 ♻️ 

## Hey Happy Coders, 👋🏽 
**This is a great project you have going on, well-done lads and thanks for implementing the changes requested earlier on**. 

### Well-done 💯 
    1. The validations have been set.

**However, there are a few sections to improve before your project is approved.** 🔴 
<hr>

### REQUIRED

- [ ] In the user model, you are validating the `name` yet you have no name column in your users table. Also, for link model, you are validating the `comment` yet no comment column exists in the link table. Run migrations while creating the missing columns so that the validations are valid.
- [ ] For the link model, you may choose to change the content validation to url validation since its what already exists in your table.
You may choose to read about migrations from the rails doc. Here is another [great article](https://www.ralfebert.de/snippets/ruby-rails/models-tables-migrations-cheat-sheet/) to help you get started.


#

### Kindly make all the requested changes and submit another CRR. 💯 

**Cheers 🍹 and Happy coding 💻** 

<hr>

Mention @mke2111 in this thread and I'll be glad to help. 😄 
### Best regards
Slack 🆘  Roy Mukuye
Twitter 🐦  [Roy Mukuye](https://twitter.com/Roymkenya)
LinkedIn 🔗  [Roy Mukuye](https://www.linkedin.com/in/roy-mukuye/)

**Review by mke2111 — CHANGES_REQUESTED** [review]
# STATUS: CHANGES REQUIRED 🔴 ♻️ 

## Hey Happy Coders, 👋🏽 

### Well-done 💯 
    1. The validations are now valid.

**However, there is one more section to improve before your project is approved.** 🔴 
<hr>

### REQUIRED

- [ ] The users' table needs a username column. This should be validated.

#

### Kindly make all the requested changes and submit another CRR. 💯 

**Cheers 🍹 and Happy coding 💻** 

<hr>

Mention @mke2111 in this thread and I'll be glad to help. 😄 
### Best regards
Slack 🆘  Roy Mukuye
Twitter 🐦  [Roy Mukuye](https://twitter.com/Roymkenya)
LinkedIn 🔗  [Roy Mukuye](https://www.linkedin.com/in/roy-mukuye/)

**Comment by prolajumokeoni** [comment]
> # STATUS: CHANGES REQUIRED  
> ## Hey Happy Coders, 👋🏽
> ### Well-done 
> ```
> 1. The validations are now valid.
> ```
> 
> **However, there is one more section to improve before your project is approved.** 
> 
> ### REQUIRED
> * [ ]  The users' table needs a username column. This should be validated.
> 
> ### Kindly make all the requested changes and submit another CRR. 
> **Cheers tropical_drink and Happy coding computer**
> 
> Mention @mke2111 in this thread and I'll be glad to help. 
> 
> ### Best regards
> Slack  Roy Mukuye
> Twitter  [Roy Mukuye](https://twitter.com/Roymkenya)
> LinkedIn  [Roy Mukuye](https://www.linkedin.com/in/roy-mukuye/)

Thanks for the review @mke21111 sent a message on slack hope to get a response, thanks!

**Review by george-shammar — APPROVED** [review]
### **STATUS:APPROVED** :heavy_check_mark: :heavy_check_mark: 

Hello Team, Thanks for adding username to the user table and validating it.

Great job :+1: 

I wish you good luck in your future projects.

Cheers :smile:

**Comment by prolajumokeoni** [comment]
thankyou @george-shammar

**Pull request closed without merging**
